version: '3'
services:
  nats-server:
    image: nats:alpine
  airline1:
    build: ./airline
    image: vinsdocker/airline
    environment:
      - NATS_SERVER=nats://nats-server:4222
      - AIRLINE_NAME=DELTA
    depends_on:
      - nats-server
  airline2:
    image: vinsdocker/airline
    environment:
      - NATS_SERVER=nats://nats-server:4222
      - AIRLINE_NAME=FRONTIER
    depends_on:
      - nats-server
  airline3:
    image: vinsdocker/airline
    environment:
      - NATS_SERVER=nats://nats-server:4222
      - AIRLINE_NAME=UNITED_AIRLINE
    depends_on:
      - nats-server
  flight-search:
    build: ./flight-search
    image: vinsdocker/flight-search
    depends_on:
      - nats-server
    ports:
      - "8080:8080"
    environment:
      - NATS_SERVER=nats://nats-server:4222